# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 685c153b96b53969586d4f26f5aecd90b59a40c17ee2315399f774f22be17ee2586bb739b43036880107d2281d815735ffa8a7e43f62dcb04c55907621856443

test:
  secret_key_base: be0d59039260c632417da293099dc3e278c184e3e0c765d71f47d8ae229ceddeaac11f92f95d76fc8d4787161b5ecd1f4dd2b1ca98ea9705b0d307535ce0b12c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
